### ISSUE TITLE
"Path to long" error when extracting .zip

### ISSUE THREAD

**Issue by brian-swan** [Azure/azure-sdk-for-php#127]
When downloading then extracting the .zip archive for the SDK, I get an error: "An unexpected error is keeping you from copying the file." The error info is: 0x80010135: Path too long. The file in question is TableSharedKeyAuthenticationSchemeMock.php.

**Comment by gamicklisafisher** [comment]
For copying and deleting “Long Path Tool” software should be try, many articles refer this for such solutions.
