### ISSUE TITLE
Move license for Client example into the code block

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-sdk-for-php#639]
When using the TaskList sample, and viewing the page source, an extra copyright and license appear in the file. That is because the code references `Client\Client.php`, which specifies the copyright as an HTML comment outside of the code block.

It would be better to follow what is done in the rest of the PHP source code, where the Client's copyright is inside of the PHP code block, so it does not get rendered in the source of the page.

(It is fine for the copyright to appear in the Tasklist page source, because that is intended to be consumed as a HTML page.)

**Comment by yaqiyang** [comment]
Issue has been resolved
