### ISSUE TITLE
CloudSubscription sample is broken

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-sdk-for-php#640]
When using the TaskList sample, it was failing because of errors in the `CloudSubscription` class. Things I had to change:

* Change location from `SOUTH_CENTRAL_US` to `WEST_US` (but that might be because of my test account doesn't have access to S_C_US)
* `_blockUntilAsyncFinish` needs to accept a full result, not the result's request id.
* The properties obtained from `getStorageServiceProperties` are not the real properties; the result is returned. Need to add this line:
    ```
    $properties = $properties->getStorageService();
    ```

**Comment by yaqiyang** [comment]
This example has been fixed. Please re-open it if you see other problems. 

Thanks
yaqi
