### ISSUE TITLE
QueryEntitiesOptions ignores filter

### ISSUE THREAD

**Issue by brian-swan** [Azure/azure-sdk-for-php#641]
When I pass a filter directly to the queryEntities method, I get results that show the filter was applied. However, when I use a QueryEntitiesOptions object and pass the same filter to it, the results indicate that the filter was ignored. For example, this returns the expected data in the partition1 (notice I'm passing the filter directly):
 
  $filter = "PartitionKey eq 'partition1'";
  $result = $tableRestProxy->queryEntities("mytable", $filter);
 
But if I set the filter in an $options object, the filter is ignored (I get results as if I'd passed an empty filter...in my case, all data from partition0 is returned):
 
  $filter = "PartitionKey eq 'partition1'";
  $options = new QueryEntitiesOptions();
  $options->setFilter($filter);
  $result = $tableRestProxy->queryEntities("mytable", $options);

**Comment by yaqiyang** [comment]
We have setFilter() methods in the following classes,
ServiceBus\Models\RuleDescription.php
ServiceBus\Models\RuleInfo.php
Table\Models\Query.php
Table\Models\QueryEntitiesOptions.php
Table\Models\QueryTablesOptions.php
Table\TableRestProxy.php

They all take filter as Filter type object, not strings. Can you let me know where we are taking filter as string?
Thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
