### ISSUE TITLE
SB Queue description chokes on XML with duplicate elements in the description

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-sdk-for-php#648]
Although I have no idea how Service Bus interprets this XML, it is valid for a client to upload this:
```xml
<QueueDescription xmlns="http://schemas.microsoft.com/netservices/2010/10/servicebus/connect" xmlns:i="http://www.w3.org/2001/XMLSchema-instance">
    <DeadLetteringOnMessageExpiration>false</DeadLetteringOnMessageExpiration>
    <DeadLetteringOnMessageExpiration>false</DeadLetteringOnMessageExpiration>
    <DefaultMessageTimeToLive>P10675199DT2H48M5.4775807S</DefaultMessageTimeToLive>
    <DuplicateDetectionHistoryTimeWindow>PT10M</DuplicateDetectionHistoryTimeWindow>
    <EnableBatchedOperations>true</EnableBatchedOperations>
    <LockDuration>PT1M</LockDuration>
    <LockDuration>PT30S</LockDuration>
    <MaxDeliveryCount>10</MaxDeliveryCount>
    <MaxSizeInMegabytes>1</MaxSizeInMegabytes>
    <MaxSizeInMegabytes>1024</MaxSizeInMegabytes>
    <MessageCount>0</MessageCount>
    <RequiresDuplicateDetection>false</RequiresDuplicateDetection>
    <RequiresDuplicateDetection>true</RequiresDuplicateDetection>
    <RequiresSession>false</RequiresSession>
    <RequiresSession>false</RequiresSession>
    <SizeInBytes>0</SizeInBytes>
</QueueDescription>
```
(This was uploaded by one of the other SDKs I'm working on :-(  )

The problem is that in QueueDescription.create, we have this code
```php
        if (array_key_exists('LockDuration', $queueDescriptionArray)) {
            $queueDescription->setLockDuration(
                (string)$queueDescriptionArray['LockDuration']
            );
        }
```
When there are duplicate LockDuration elements, `$queueDescriptionArray['LockDuration']` returns an array instead of a string, which causes this error to be thrown:
```
1) Tests\Functional\WindowsAzure\ServiceBus\
ServiceBusTopicTest::testSubscriptionTopic
Array to string conversion

...\WindowsAzure\ServiceBus\Models\QueueDescription.php:142
...\WindowsAzure\ServiceBus\Models\QueueInfo.php:102
...\WindowsAzure\ServiceBus\Models\ListQueuesResult.php:64
...\WindowsAzure\ServiceBus\ServiceBusRestProxy.php:494
...\tests\functional\WindowsAzure\ServiceBus\IntegrationTestBase.php:56
...\tests\functional\WindowsAzure\ServiceBus\IntegrationTestBase.php:43
```
Commenting out the failing line leads to failures in the other places where duplicated elements are accessed. 

I believe that there are other places in the SDK where we have addressed this issue using a helper method. Perhaps we can reuse that logic here. 

We would have to sync with the SB team or do some research to find which elements we should take: first? last? middle?

**Comment by yaqiyang** [comment]
@jcookems , I understand this has been a long time. Do you still have this issue unresolved?

Thanks
Yaqi

**Comment by jcookems** [comment]
Give it a try and let me know

**Comment by yaqiyang** [comment]
I found a copy of the schema at http://grepcode.com/file/repo1.maven.org/maven2/org.plannerstack/sbproxy/1.2.0/schemas.microsoft.com.netservices.2010.10.servicebus.connect.xsd. LockDuration should be [0..1]. It is possible that ServiceBus did not validate your xml, but this should not be a bug in the PHP SDK. 

yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
