### ISSUE TITLE
improve the default lock duration

### ISSUE THREAD

**Issue by gcheng** [Azure/azure-sdk-for-php#655]
http://stackoverflow.com/questions/14137160/azure-service-bus-peeklock-is-timing-out-after-just-five-seconds

I got a reply from the Azure support team, who quickly figured out that the Azure portal isn't persisting the lock duration that's selected when creating a queue. The default expiry is apparently five seconds (although I couldn't find any references to this default value in any of the docs, which is annoying) which is why it was timing out.

So anyway, the dev team are apparently working on a fix, and everything should be working soon.

**Comment by yaqiyang** [comment]
@gcheng , is this still an issue for you? Is this anything we can implement in the PHP SDK?

Thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
