### ISSUE TITLE
createBlobBlock failed with https protocol, not http

### ISSUE THREAD

**Issue by ygrenier** [Azure/azure-sdk-for-php#664]
Hi,

When we use the BlobRestProxy::createBlobBlock() method with an "https" endpoint protocol after an amount of data (apparently 5Mb) an error is thrown :

    PHP Warning:  fwrite(): SSL: Connection reset by peer in /usr/share/php/HTTP/Request2/SocketWrapper.php on line 188
    PHP Fatal error:  Uncaught HTTP_Request2_MessageException: Error writing request in /usr/share/php/HTTP/Request2/Adapter/Socket.php on line 899
    #0 /usr/share/php/HTTP/Request2/Adapter/Socket.php(899): HTTP_Request2_SocketWrapper->write('ABCDEFGHIJKLMNO...')
    #1 /usr/share/php/HTTP/Request2/Adapter/Socket.php(150): HTTP_Request2_Adapter_Socket->writeBody()
    #2 /usr/share/php/HTTP/Request2.php(959): HTTP_Request2_Adapter_Socket->sendRequest(Object(HTTP_Request2))
    #3 /home/deuxsucres/lib/azure-sdk-for-php/WindowsAzure/Common/Internal/Http/HttpClient.php(262): HTTP_Request2->send()
    #4 /home/deuxsucres/lib/azure-sdk-for-php/WindowsAzure/Common/Internal/RestProxy.php(141): WindowsAzure\Common\Internal\Http\HttpClient->send(Array, Object(WindowsAzure\Common\Internal\Http\Url))
    #5 /home/deuxsucres/lib/azure-sdk-for-php/WindowsAzure/Common/Internal/ServiceRestProxy.php(86): WindowsAzure\Common\Internal\RestProxy->sendContext(Object(WindowsAzure\Common\Internal\Http\HttpCallContext))
    #6 /home/deuxsucres/lib/azure-sdk-for-php/WindowsAzure/ in /usr/share/php/HTTP/Request2/SocketWrapper.php on line 192

For example I put blocks of 2Mb, the first and second blocks are correctly sent, but the third call throw error after a 90 seconds pause.

If I change the endpoint protocol to "http" there is no problem,

I trying on 3 differents servers all on Ubuntu 12 or 13, install via PEAR or with code source.

Best regards,

Yanos

**Comment by yaqiyang** [comment]
This should have been fixed by https://github.com/Azure/azure-sdk-for-php/pull/787. Please re-open the issue if otherwise. 

Thanks
Yaqi
