### ISSUE TITLE
Support Renew-lock on WindowsAzure\ServiceBus\Models\BrokeredMessage

### ISSUE THREAD

**Issue by borrel** [Azure/azure-sdk-for-php#666]
when having long(over 5 min) operations the lock on the message lock must be renewable

[rest api page]( http://msdn.microsoft.com/en-us/library/windowsazure/jj839746.aspx)
[dot net documentation](http://msdn.microsoft.com/en-us/library/windowsazure/microsoft.servicebus.messaging.brokeredmessage.renewlock.aspx)

thanks

**Comment by yaqiyang** [comment]
@borrel , is this still an issue for you?

Thanks
Yaqi

**Comment by borrel** [comment]
@yaqiyang , no it is not.

I'm not using azure anymore.

thank you for your message

**Comment by yaqiyang** [comment]
@borrel , sorry to hear that. Azure has been improved significantly since then and so does our SDK. Hope you can try again and let us know how we can help. 

Sincerely,
Yaqi Yang

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
