### ISSUE TITLE
ListHostedServices() does return an Array but its missing propperties.

### ISSUE THREAD

**Issue by hvakees** [Azure/azure-sdk-for-php#676]
Whenever i call the ListHostedServices() function I get an array returned but the array is missing some properties. For example, the property 'status' isn't returned.

http://msdn.microsoft.com/en-us/library/windowsazure/ee460781.aspx

I hope you can explain on how to retrieve the other properties

Kind regards,

Kees Leek

**Comment by yaqiyang** [comment]
@hvakees. This issue should have been resolved with the newest code. If not, please let us know. 

Thanks
yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
