### ISSUE TITLE
Must satisfy is_string exception for double

### ISSUE THREAD

**Issue by omkarkhair** [Azure/azure-sdk-for-php#678]
I'm inserting an entity in Azure Table, one of the properties is a `integer`, and the Edm type is set appropriately.

I get an exception

` Uncaught exception 'InvalidArgumentException' with message ''demand' property value must satisfy is_string.'`

the property is set as a double correctly. The exception is thrown on trying to add the entity. My value cannot be a string, as it has to be stored as an Int.

```
 [demand] => WindowsAzure\Table\Models\Property Object
                (
                    [_edmType:WindowsAzure\Table\Models\Property:private] => Edm.Int64
                    [_value:WindowsAzure\Table\Models\Property:private] => 42226
                )
```

**Comment by yaqiyang** [comment]
The error indicates you set the data type to Edm.String or it is null which defaults to string. Please verify it. 

Thanks
Yaiq

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
