### ISSUE TITLE
PHP Composer packages issue

### ISSUE THREAD

**Issue by doggy8088** [Azure/azure-sdk-for-php#679]
When installing "microsoft/windowsazure" composer package, my box got hang when cloning repo from GitHub.  I was found that they use "git://github.com/WindowsAzure/azure-sdk-for-php.git" as the Git url.  The git protocol from GitHub looks like not so stable.  Here is the error message I got:

```
G:\>php composer.phar install
Loading composer repositories with package information
Initializing PEAR repository http://pear.php.net
Installing dependencies (including require-dev)
  - Installing microsoft/windowsazure (dev-master 74a0475)
    Cloning 74a0475b4fe28fbe9f73660bd9ae2248148912f9



  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone "git://github.com/WindowsAzure/azure-sdk-for-php.git" "G:\vendor\microsoft/windowsazure" && cd /D "G:\vendor\mic
  rosoft/windowsazure" && git remote add composer "git://github.com/WindowsAzure/azure-sdk-for-php.git" && git fetch composer" exceeded t
  he timeout of 300 seconds.



install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progre
ss] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
```

When I change the Git protocol from `git` to `ssh` or `https`, everything is fine.  So I suggest you change the Git protocol from `git` to `https` or `ssh`.

Thanks!

**Comment by yaqiyang** [comment]
GitHub now supplies https by default. Please re-open this if you still have issues. 

Thanks
Yaqi
