### ISSUE TITLE
Bad class constant

### ISSUE THREAD

**Issue by rdohms** [Azure/azure-sdk-for-php#699]
* `AUTHORITY_FORMAT` does not exist in: https://github.com/WindowsAzure/azure-sdk-for-php/blob/master/WindowsAzure/ServiceBus/Internal/WrapTokenManager.php#L225

**Comment by yaqiyang** [comment]
@rdohms , is AUTHORITY_FORMAT supposed to be "grant_type=client_credentials&client_id={0}&client_secret={1}"? I could not find any documentation. Let me know if you have any ideas. 

Thanks
yaqi

**Comment by rdohms** [comment]
I have absolutely no clue what this was meant to be. I was just doing some static analysis and that came out as obvious, also 2 years ago, that is way too long to reply to anything and expect me to remember :P
