### ISSUE TITLE
Table service cross partition boundary query

### ISSUE THREAD

**Issue by shaunfangx** [Azure/azure-sdk-for-php#702]
Table service entity query will fail to retrieve the correct response when NextPartitionKey and NextRowKey is assigned. Following is my code:

   $options = new QueryEntitiesOptions();
    $options->setFilter(Filter::applyQueryString($filter));
    $result = $tableRestProxy->queryEntities($scale, $options);

    $entities = $result->getEntities();
    $nextPK=$result->getNextPartitionKey();
    $nextRK=$result->getNextRowKey();

    echo "Count:".count($entities)." Next PK:".$nextPK." RK:".$nextRK."<br>\n";

    while ($nextPK <> NULL && $nextPK <> "" ) {
        $options = new QueryEntitiesOptions();
        $options->setFilter(Filter::applyQueryString($filter));
        $options->setNextPartitionKey($nextPK);
        $options->setNextRowKey($nextRK);
        $result = $tableRestProxy->queryEntities($scale, $options);        
        $nextPK=$result->getNextPartitionKey();
        $nextRK=$result->getNextRowKey();
        $newentities=$result->getEntities();       

        echo "Count:".count($newentities)." Next PK:".$nextPK." RK:".$nextRK."<br>\n";
        $entities=array_merge($newentities, $entities);    
    }

When the partition number is big (over 200) and partition content is big, the first query can't return all the content. So nextpartitionkey and nextrowkey is returned for follow up query. But the following query will return the same result, just like nextpartitionkey/nextrowkey is not assigned. Then the program will run intinitely

I modified following code in the sdk:
line 1007 of WindowsAzure\Table\TableRestProxy.php:
        //$encodedPK   = $this->_encodeODataUriValue($options->getNextPartitionKey());
        //$encodedRK   = $this->_encodeODataUriValue($options->getNextRowKey());
        $encodedPK   = $options->getNextPartitionKey();
        $encodedRK   = $options->getNextRowKey();

Then the result is correct. Seems _encodeODataUriValue method is not neccessary here

**Comment by yaqiyang** [comment]
@shaunfangx , do you still experience this issue?

Thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
