### ISSUE TITLE
Cannot put blob greater than 5.5 via chunk'ing

### ISSUE THREAD

**Issue by MikeyF-Anovia** [Azure/azure-sdk-for-php#711]
A reply to this post suggested I submit an issue:
http://social.technet.microsoft.com/Forums/windowsazure/en-US/ff164062-c88b-446e-8eea-69fd238a1829/put-blobs-of-size-greater-than-55mb-fail-with-https-but-not-http?forum=windowsazuredata&prof=required

I did not create that post, but am encountering the same problem with the azure php sdk and have tried setting the UploadThresholdInBytes to 1 MB via:
  $restProxy->setSingleBlobUploadThresholdInBytes(1048576); //1MB
  $restProxy->createBlockBlob($container, $blobName, $blob, $props);
and on the 6th iteration of the loop on line 1326 of BlobRestProxy:
  $this->createBlobBlock($container, $blob, $block->getBlockId(), $body);
it hangs for about 3 minutes and then a php warning is thrown: Warning 2 fwrite(): SSL: Broken pipe app/Lib/PEAR/HTTP/Request2/SocketWrapper.php line 202.

Because of that failure in SocketWrapper->write(), a  HTTP_Request2_MessageException('Error writing request') is thrown and the file/blob is not uploaded to azure blob storage. 

Mikey

**Comment by yaqiyang** [comment]
This has been fixed https://github.com/Azure/azure-sdk-for-php/pull/787
