### ISSUE TITLE
Error occurs when uploading the file to the windows azure storage on nginx web server

### ISSUE THREAD

**Issue by joinqi** [Azure/azure-sdk-for-php#714]
On nginx web server, according to the following in [sample code](http://azure.microsoft.com/en-us/documentation/articles/storage-php-how-to-use-blobs/#UploadBlob),  upload a 5 KB file, an exception is as follows 
```xml
<?xml version="1.0" encoding="utf-8"?>
<Error>
      <Code>InvalidHeaderValue</Code>
     <Message>The value for one of the HTTP headers is not in the correct format.RequestId:2ca93ad8-e91d-420c-8f8d-9a5dedb9caedTime:2014-07-11T08:22:22.6457958Z</Message>
     <HeaderName>Content-Length</HeaderName>
     <HeaderValue>0</HeaderValue>
</Error>
```
After examination,  at run time, last received `$body` length is zero in 1309 lines  in the file BlobRestProxy.php, this is obviously wrong.
``` php
$body = fread ($content, $blockSize); 
```

My solution is to add the following code  below the above line of code
```php
If (strlen ($body) = = 0) { 
     $end = 1; 
     continue; 
} 
```
Not sure if this solution is correct or not.

**Comment by muhammet** [comment]
+1

**Comment by yaqiyang** [comment]
It has been fixed by https://github.com/Azure/azure-sdk-for-php/commit/c9f6aeddb2c69fe11ced9d4f54461c5dcf5509ec
