### ISSUE TITLE
Installation via Composer using dist is broken

### ISSUE THREAD

**Issue by joelfillmore** [Azure/azure-sdk-for-php#719]
Source install is working, but for dist install the zip file url was returning 404. I finally realized it was because the repo url has changed from WindowsAzure/azure-sdk-for-php to Azure/azure-sdk-for-php. The Composer package still has the old url. 

Source installs work because the old repository url (git@github.com:WindowsAzure/azure-sdk-for-php.git) will redirect to the new url. However, the zip file for the old url doesn't redirect.

I was able to work around this by manually fixing up the repository names in my composer.lock file. I'm assuming that Composer auto-generates the zip file url using the github repository link. So hopefully fixing this just requires the Composer package owner to update the repository link.

**Comment by devigned** [comment]
related to #747

**Comment by yaqiyang** [comment]
This has been fixed. Please let me know if you have still issues here.

Thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
