### ISSUE TITLE
 Diagnostics for Azure and PHP Cloud Services

### ISSUE THREAD

**Issue by bayfall** [Azure/azure-sdk-for-php#721]
We're having issues with setting up Diagnostics for Azure with PHP Cloud Services 

No matter where we put the diagnostics.wadcfg (bin or root folder) it get's ignored and only the default configuration is  generated in the storage we use for diagnostics in the wad-control-container. 

Besides when we RDP to the box all the Powershell commands like this fail 
    Add-PsSnapin PHPManagerSnapin
and none of the Azure RoleEnvironment Variables are set.
Making it hard to update our php.ini accordingly

We've been struggling for quite a while with this diagnostics setup for php, unlike with C#. So any help would be appreciated as this is blocking us at the moment.

Cheers

**Comment by yaqiyang** [comment]
Do you have this issue?

Thanks
Yaqi

**Comment by yaqiyang** [comment]
You might not have the correct connection string in the .cscfg file. Please re-open the issue if it is not resolved. 

Thanks
Yaqi
