### ISSUE TITLE
RoleEnvironment::isAvailable returning false when in Azure environment on Linux VM

### ISSUE THREAD

**Issue by ckimrie** [Azure/azure-sdk-for-php#722]
Currently struggling with the RoleEnvironment class and its use in the Azure environment. The VMs are running Ubuntu 14 (selected from the available VM gallery).

My setup involves an Azure cloud that contains two availability sets (website, worker). The two VM types have been created from captured images (and the waagent deprovisioning instructions have been followed).

I am looking to obtain the ID or some other form of VM instance specific identifier. It is my understanding that `RoleEnvironment::getCurrentRoleInstance()->getId()` (this has been abbreviated) should get me what I need.

My problem is that the call above is throwing an exception and the `RoleEnvironment::isAvailable()` always returns false, even when running in the Azure environment.

I have struggled to find official usage docs on the RoleEnvironment class, so have determined the above by simply scanning the source code. Can anyone tell me if I am missing a piece of the jigsaw?

Currently think it could be one of the following:
* The `waagent -deprovision` in order to create a reusable VM image has messed up the azure SDKs ability to phone home or talk to the Azure environment
* Connection details or account details must be provided somewhere as environment variables (or similar) and I dont know about it.
* The RoleEnvironment is not what I think it is and I am chasing my own tail
* The RoleEnvironment simply doesnt work (see http://stackoverflow.com/questions/12364573/unable-to-query-roleenvironment-with-windows-azure-sdk-for-php)

Any help much appreciated

**Comment by yaqiyang** [comment]
Do you still have this issue?

Thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
