### ISSUE TITLE
Channel, Program and StreamEndpoints not available.

### ISSUE THREAD

**Issue by benbowler** [Azure/azure-sdk-for-php#723]
These methods aren't available on the current API. When is this likely to be added?

**Comment by yaqiyang** [comment]
Can you be more specific? Media Services API has been added since then. Please let me know if that takes care of your concerns. 
Thanks
yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
