### ISSUE TITLE
Canonical URL on Packagist is out of date

### ISSUE THREAD

**Issue by SyntaxC4** [Azure/azure-sdk-for-php#724]
The Canonical URL on [Packagist](https://packagist.org/packages/microsoft/windowsazure) still points to the WindowsAzure organization which is now causing the installations of the SDK to fail.

**Comment by yaqiyang** [comment]
If you follow the current steps from readme.md, all packages will be installed correctly. Let me know if you still have issues there.

Thanks
yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
