### ISSUE TITLE
Operations on HTTPS do not work correctly

### ISSUE THREAD

**Issue by RobDonovan** [Azure/azure-sdk-for-php#728]
Hi,

I've now found another situation where the PHP SDK does not function correctly when using the https protocol.

Is someone looking at this SDK to fix the problems with using https?

As it seems totally broken if you wish it to be secure :(

There is currently the > 5.5mb upload issue that is logged with no fix, and now I've found this new one.

The following script fails after doing 451 renames. It works fine if the protocol is http.

I really think this SDK needs to have some better support, as it seems its just left to 'rot' at the moment :(

This is the script, you need a blob 'rob-new-0.jpg' in a container 'stock-images' to be present before running it.

It fails on the copyBlob command. If I check the $logs, then the one it fails on has actually worked fine, and the CopyBlob,CopyBlobSource & CopyBlobDestination commands are logged ok, with no errors, but the socket pauses for 3 minutes and then gets the exception, even though that copyBlob worked fine.

        define('AZURE_ACCOUNT','xxxxxxxx');
        define('AZURE_ACCOUNT_KEY','xxxxxxx');
        define('AZURE_PROTOCOL','https');

        set_include_path('/home/system/www/phpLibs/azure');
        require_once 'WindowsAzure/WindowsAzure.php';

        use WindowsAzure\Common\ServicesBuilder;

        for ($i=0;$i<500;$i++) {
                print "processing: ".$i."\n";
                $oldURL = 'rob-new-'.$i.'.jpg';
                $newURL = 'rob-new-'.($i+1).'.jpg';

                renameit($oldURL,$newURL);
        }

        function renameit($oldURL,$newURL) {

                $connectionString = 'DefaultEndpointsProtocol='.AZURE_PROTOCOL.';AccountName='.AZURE_ACCOUNT.';AccountKey='.AZURE_ACCOUNT_KEY;
                $blobRestProxy = ServicesBuilder::getInstance()->createBlobService($connectionString);

                $blobContainer = 'stock-images';
                $blobRestProxy->copyBlob($blobContainer, $newURL, $blobContainer, $oldURL);
                $blobRestProxy->deleteBlob($blobContainer, $oldURL);

        }

After 451 iterations, it pauses for about 3 minutes, and then fails with:

        PHP Fatal error:  Uncaught HTTP_Request2_MessageException: Malformed response:  in /home/system/www/phpLibs/azure/HTTP/Request2/Adapter/Socket.php on line 1014
        #0 /home/system/www/phpLibs/azure/HTTP/Request2/Adapter/Socket.php(1014): HTTP_Request2_Response->__construct('', true, Object(Net_URL2))
        #1 /home/system/www/phpLibs/azure/HTTP/Request2/Adapter/Socket.php(137): HTTP_Request2_Adapter_Socket->readResponse()
        #2 /home/system/www/phpLibs/azure/HTTP/Request2.php(941): HTTP_Request2_Adapter_Socket->sendRequest(Object(HTTP_Request2))
        #3 /home/system/www/phpLibs/azure/WindowsAzure/Common/Internal/Http/HttpClient.php(262): HTTP_Request2->send()
        #4 /home/system/www/phpLibs/azure/WindowsAzure/Common/Internal/RestProxy.php(141): WindowsAzure\Common\Internal\Http\HttpClient->send(Array, Object(WindowsAzure\Common\Internal\Http\Url))
        #5 /home/system/www/phpLibs/azure/WindowsAzure/Common/Internal/ServiceRestProxy.php(86): WindowsAzure\Common\Internal\RestProxy->sendContext(Object(WindowsAzure\Common\Internal\Http\HttpCallContext))
        #6 / in /home/system/www/phpLibs/azure/HTTP/Request2/Response.php on line 215

I'm beginning to think my decision to use Azure and PHP was a bad idea, and I need to move my application to somewhere else like Amazon or Google. But that is going to take some time and effort, and I would much prefer someone at Azure to fix their SDK so it works more solidly.

**Comment by RobDonovan** [comment]
It doesnt seem to be limited to just copyBlob.

Seems to be any blob operation that is repeated within a script will eventually fail if you are using HTTPS.

After about 900 iterations of this, it fails the same way:

>$blob = $blobRestProxy->getBlob($container,$row[2]);
>$contents = stream_get_contents($blob->getContentStream());

Works fine if you connect with http.

So, looks like the php SDK is rather unsecure, if the only way to use it reliably is to use http :(

And still no response?

**Comment by AntJones** [comment]
I'm having the same problem using HTTPS, any update on this issue?

**Comment by RobDonovan** [comment]
The only thing I can find to 'fix' it, is to write your own copyBlob/deleteBlob/getBlob using PHP Curl and directly access the REST API.

The problem seems to be with this SDK and the socket method it uses, but the REST API directly is ok.

I've had to do that with several other methods from this SDK, as there just seems too much wrong with it to use it in any real kind of environment.

Havent done it for the rename yet as I was only having to use it as a util at the time (and temp changed it to use http to get it to work), and I havent had chance to rewrite it without using the SDK yet.

**Comment by AntJones** [comment]
Hi RobDonovan, thanks for the information, I'll create some Curl functions and see how I get on!

**Comment by euskadi31** [comment]
Hi,

I the same problem !!

**Comment by nowenL** [comment]
Hi, Everyone

I tried to upload a file > 5.5M with https but can't reproduce this issue. Can you share more information about the environment. What's the OS, the php version and the HTTP_Request2 version are used here?

**Comment by AntJones** [comment]
Hi  NowenL,
The test server I'm using is running Centos 7 with PHP 5.3.3 with openssh

**Comment by RobDonovan** [comment]
Hi,

Sorry, dont have time to retest and try it, since I've moved away from Azure SDK now, but when I found this I think I was on Ubuntu 3.13.0-61-generic, php 5.5.9 with openssh 6.6.1p1 and HTTP_Request 2.2.1

HTHs.

**Comment by nowenL** [comment]
Hi, Jones & Rob

Thanks for the information. This bug was fixed months ago, I think that's why I can't repro it under the same scenario;
http://stackoverflow.com/questions/22419256/azure-block-blob-put-fails-when-using-https

**Comment by yaqiyang** [comment]
I cannot repro this issue.  Please re-open it if you can still reproduce it.
