### ISSUE TITLE
Not properly encoding message content

### ISSUE THREAD

**Issue by agilbert201** [Azure/azure-sdk-for-php#730]
We are having issues with posting messages in JSON string representation that are not properly encoded. The message content is put onto the queue as for example:

"{\"topic\":\"foo\"}" with base64 encoding set.

If you try to read message content with anything other than PHP SDK you will get a format exception, as System.Convert.FromBase64String is getting called and fails on this (as it is not a base64 encoded string).

**Comment by yaqiyang** [comment]
@agilbert201 , can you give me more context on this problem? do you have the same issue when you use anything else to ready the message content?

**Comment by agilbert201** [comment]
It has been a while, and was for a client trying to integrate. I had them use a curl library instead and gave them stubs to go straight against the REST API.

I think the core issue was within the XML submitted to the queue the message content itself needs to be Base64 encoded (to avoid XML issues). And this wasn’t roundtripping properly.

Sorry can’t help more. As long as that “works” then it’s good.


Andrew Gilbert
andy@agilbert.net
802.426.2108 (h)
802.793.9447 (m)
802.535.1653 (voice mail)

**Comment by yaqiyang** [comment]
I am closing this issue unless we find more repros. Thanks a lot for using PHP Azure SDK.

Sincerely,
Yaqi
