### ISSUE TITLE
Fatal Error while uploading files bigger than 4GB

### ISSUE THREAD

**Issue by thorstenchristiansen** [Azure/azure-sdk-for-php#740]
When uploading large files to the blob-storage, I get the following error:
Fatal error: Uncaught exception 'WindowsAzure\Common\ServiceException' with message 'Fail:
Code: 400
Value: The specified blob or block content is invalid.

The issue is, that the string-length of the block-Id gets bigger when 1000 chunks are uploaded.
With a maximum chunk-size of 4MB this means, that no files bigger than 3996MB can be uploaded.

The problem can be solved by editing the WindowsAzure/Blob/BlobRestProxy.php.
In the function createBlockBlob() there is a line to set the block-Id:

$block->setBlockId(base64_encode(str_pad($counter++, '0', 6)));

Changing it to:

$block->setBlockId(base64_encode(str_pad($counter++, 6, '0', STR_PAD_LEFT)));

solved the problem for me.

**Comment by yaqiyang** [comment]
@thorstenchristiansen , this has been fixed by https://github.com/Azure/azure-sdk-for-php/pull/757. Please let us know if you still see issues. 

thanks
Yaqi
