### ISSUE TITLE
SB Queue unlockMessage not working

### ISSUE THREAD

**Issue by avionwd** [Azure/azure-sdk-for-php#742]
When use lock duration for message (the same as in manual):

```php
$options = new ReceiveMessageOptions();
$options->setPeekLock();

$message = $proxy->receiveQueueMessage('queue_name', $options)
```

I have some exception while processing results, and use `unlockMessage` method after catch it. But this message is hanged in queue and not accessible by `receiveQueueMessage` method anymore.
At the portal queue length show's all messages with blocked.

**Comment by yaqiyang** [comment]
What exceptions are they? The problem could be related to the type of exceptions. 

yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
