### ISSUE TITLE
Error on composer update

### ISSUE THREAD

**Issue by pdewouters** [Azure/azure-sdk-for-php#743]
```
Initializing PEAR repository http://pear.php.net
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - microsoft/windowsazure v0.4.1 requires pear-pear2.php.net/http_request2 * -> no matching package found.
    - microsoft/windowsazure v0.4.0 requires pear-pear/http_request2 * -> no matching package found.
    - microsoft/windowsazure dev-storage-2012-02-12 requires pear-pear/http_request2 * -> no matching package found.
    - microsoft/windowsazure dev-master requires pear-pear2.php.net/http_request2 * -> no matching package found.
    - microsoft/windowsazure dev-dev requires pear-pear2.php.net/http_request2 * -> no matching package found.
    - Installation request for microsoft/windowsazure * -> satisfiable by microsoft/windowsazure[dev-dev, dev-master, dev-storage-2012-02-12, v0.4.0, v0.4.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

my composer.json file

```
{
  "name": "name",
  "description": "desc",
  "authors": [
    {
      "name": "me",
      "email": "me@me.com"
    }
  ],
  "require": {
    "microsoft/windowsazure": "*",
    "pimple/pimple": "~3.0",
  },
  "repositories": [
    {
      "type": "pear",
      "url": "http://pear.php.net"
    }
  ],
  "minimum-stability": "dev"
}
```

This suggestion seems to provide a fix, `composer update` now finishes successfully

http://stackoverflow.com/a/22331110

Maybe you need to update the instructions or the composer file?

**Comment by atrauzzi** [comment]
Think I'm encountering this as well.  Any chance this project could switch to using the composer-version of the dep?

**Comment by yellow1912** [comment]
For now, you can clone it then edit and override the path in your composer file. Once they fix the issue you can just remove the override.

**Comment by tibahut** [comment]
I've made a PR to fix this : https://github.com/Azure/azure-sdk-for-php/pull/741/files

You can try this in your composer.json until Microsoft releases a new version : 
```
"repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net",
            "vendor-alias": "pear-pear2.php.net"
        }
    ],
"require": {
     "pear-pear.php.net/HTTP_Request2": "*",
        "pear-pear.php.net/mail_mime": "*",
        "pear-pear.php.net/mail_mimedecode": "*",
        "microsoft/windowsazure": "0.4.1",
...
```

**Comment by jakerb** [comment]
Above didn't work for me, manages to get around it with:

<pre>
{
    "name": "this/that",
    "description": "Lorem ipsum dolor sit amet.",
    "authors": [
        {
            "name": "Lorem Ipsum",
            "email": "lorem@ipsum.com"
        }
    ],
    "repositories": [
         {
             "type": "pear",
             "url": "http://pear.php.net",
             "vendor-alias": "pear-pear2.php.net"
         }
     ],
    "require": {
        "twig/twig": "~1.0",
        "pear-pear.php.net/HTTP_Request2": "0.4.0",
        "pear-pear.php.net/mail_mime": "*",
        "pear-pear.php.net/mail_mimedecode": "*",
        "microsoft/windowsazure": "0.4.1"
    }
}

</pre>

**Comment by tibahut** [comment]
Okay, very strange but if it works ^^
Because `microsoft/windowsazure`'s composer.json require "pear-pear.php.net/HTTP_Request2": "*".

**Comment by carbontwelve** [comment]
Its 2016, why is this not yet fixed?

**Comment by sketchthat** [comment]
+1 getting the same error.


My composer has all the following installed but I still receive;

```
        "pear-pear.php.net/mail_mime": "^1.10",
        "pear-pear.php.net/http_request2": "^2.3",
        "pear-pear.php.net/mail_mimedecode": "^1.5",
        "pear-pear.php.net/HTTP_Request2": "^2.3"
```
```
Problem 1
    - Installation request for microsoft/windowsazure ^0.4.1 -> satisfiable by microsoft/windowsazure[v0.4.1].
    - microsoft/windowsazure v0.4.1 requires pear-pear2.php.net/http_request2 * -> no matching package found.
```

**Comment by tibahut** [comment]
Have you tried my fix ?

`"repositories": [
        {
            "type": "pear",
            "url": "http://pear.php.net",
            "vendor-alias": "pear-pear2.php.net"
        }
    ],
"require": {
     "pear-pear.php.net/HTTP_Request2": "*",
        "pear-pear.php.net/mail_mime": "*",
        "pear-pear.php.net/mail_mimedecode": "*",
        "microsoft/windowsazure": "0.4.1",
...`

**Comment by devigned** [comment]
@yaqiyang and @YuvalMazor this is related to: https://github.com/Azure/azure-sdk-for-php/issues/747

**Comment by yaqiyang** [comment]
This has been fixed
