### ISSUE TITLE
Broken pipe socket error when polling azure table

### ISSUE THREAD

**Issue by franckt** [Azure/azure-sdk-for-php#744]
i currently poll an Azure queue every 5s, sometimes i get this issue :

Notice:  fwrite(): send of 487 bytes failed with errno=32 Broken pipe in /home/azureuser/geolys/vendor/pear-pear.php.net/HTTP_Request2/HTTP/Request2/SocketWrapper.php on line 202
PHP Fatal error:  Uncaught HTTP_Request2_MessageException: Error writing request in /home/azureuser/geolys/vendor/pear-pear.php.net/HTTP_Request2/HTTP/Request2/Adapter/Socket.php on line 130
#0 /home/azureuser/geolys/vendor/pear-pear.php.net/HTTP_Request2/HTTP/Request2/Adapter/Socket.php(130): HTTP_Request2_SocketWrapper->write('GET /venuesjobs...')
#1 /home/azureuser/geolys/vendor/pear-pear.php.net/HTTP_Request2/HTTP/Request2.php(939): HTTP_Request2_Adapter_Socket->sendRequest(Object(HTTP_Request2))
#2 /home/azureuser/geolys/vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/HttpClient.php(262): HTTP_Request2->send()
#3 /home/azureuser/geolys/vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/RestProxy.php(141): WindowsAzure\Common\Internal\Http\HttpClient->send(Array, Object(WindowsAzure\Common\Internal\Http\Url))
#4 /home/azureuser/geolys/vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/ServiceRestProxy.php(86): WindowsAzure\Common\Internal\RestProxy->sendContext(Object(WindowsAzure\Common\Int in /home/azureuser/geolys/vendor/pear-pear.php.net/HTTP_Request2/HTTP/Request2/SocketWrapper.php on line 206

**Comment by yaqiyang** [comment]
@franckt , do you still experience this issue?

thanks
Yaqi

**Comment by yaqiyang** [comment]
Please reopen the issue if you get this problem again.

Thanks
Yaqi
