### ISSUE TITLE
Please fix your PHPDOC typing

### ISSUE THREAD

**Issue by robertkraig** [Azure/azure-sdk-for-php#746]
I ran into an error from the obj.

    /**
     * @param $settings
     *
     * @return \WindowsAzure\Common\Internal\RestProxy|\WindowsAzure\MediaServices\MediaServicesRestProxy
     */
    public function createMediaServicesService($settings)

that is the corrected version, it was set to:

    /**
     * Builds a media services object.
     *
     * @param WindowsAzure\Common\Internal\MediaServicesSettings $settings The media
     * services configuration settings.
     *
     * @return WindowsAzure\MediaServices\Internal\IMediaServices
     */

You cannot return an Interface, you return objects which implement an interface.

**Comment by yaqiyang** [comment]
That should be as expected. When an interface is said to be returned, it always means an object that implements that interface will be returned. Let me know if you don't agree. 

Thanks
Yaqi
