### ISSUE TITLE
Blob storage - preferred way to represent an empty folder

### ISSUE THREAD

**Issue by zaak** [Azure/azure-sdk-for-php#749]
I know this question doesn't really fit the philosophy of Azure Cloud Storage, as it's a flat virtual filesystem without folder hierarchy. The integration I'm working on requires this possibility though. Amazon S3 for example allows for this by adding a `/` at the end of the the key. I've tried this, but the downside is that these dummy *directories* are listed as regular blobs in Azure management console. Is there any better - preferred way to represent an empty subdirectory in a container?

**Comment by yaqiyang** [comment]
Adding / is still the current way of representing folders in Azure. Why do you need to have empty folders in a container?

**Comment by zaak** [comment]
@yaqiyang: Creating folders is one of the core features of our file manager application ([CKFinder](https://cksource.com/ckfinder/demo)). It works a similar way like regular OS file manager, so for example to copy a file to a folder, the folder must be present.

We already resolved this by adding `/` to the end of keys that should represent folders. I think we can close this issue.
