### ISSUE TITLE
Create a new tag with a valid composer file

### ISSUE THREAD

**Issue by sescandell** [Azure/azure-sdk-for-php#750]
Hi there,

For now, tag 0.4.1 is not usable because of a wrong composer file (requesting a pear**2**.php.net URL)
A fix have been pushed through commit 8c03011ec97b3d4d938841f1a637ae40eeb03127.

Could you please create a new 0.4.2 tag just including the 8c03011ec97b3d4d938841f1a637ae40eeb03127 patch?

Dev branch is working well, but not master neither 0.4.1 tag.

Many thanks!

**Comment by jeroenseegers** [comment]
Bump.

**Comment by SInCE** [comment]
The pear-requirements issue has been resolved https://github.com/Azure/azure-sdk-for-php/issues/747, but a new tag is still missing.

:+1: for v0.4.2

**Comment by carbontwelve** [comment]
:+1:

**Comment by phansys** [comment]
This also can be early addressed as a hotfix if the development version (`master` branch) can be referenced with a branch alias as proposed in #769, since this issue is already fixed at @9f961542.

**Comment by devigned** [comment]
related to: #747

**Comment by yaqiyang** [comment]
Fixed by new version .4.2
