### ISSUE TITLE
windows-azure-storage plugin for wordpress

### ISSUE THREAD

**Issue by fabianhenzler** [Azure/azure-sdk-for-php#753]
Could anyone lease support with this issue https://wordpress.org/support/topic/http-errors-on-upload

It's the first step of every Wordpress user, using Azure and trust me, when it was working it was awesome! Sadly it's completely broken and outdated since WP4.3 :(
I'd love to help, but I don't know where to start. Something with the httpclient() seems to be wrong :/
The plugin also doesn't follow your guidelines with the php sdk anymore, so it's really hard to digg into it :(

Please @azure help us back into awesomeness again :)

**Comment by yaqiyang** [comment]
It seems the problem has been resolved. Please re-open the issue if otherwise.

Thanks
Yaqi
