### ISSUE TITLE
Fail to upload large files

### ISSUE THREAD

**Issue by icedream728** [Azure/azure-sdk-for-php#754]
When I try to upload large files using Azure storage sdk, I get error "The specified blob or block content is invalid."
I have searched and found it is bug as incorrect usage of the str_pad function.
You can find more details here:
https://social.msdn.microsoft.com/Forums/en-US/ff164062-c88b-446e-8eea-69fd238a1829/put-blobs-of-size-greater-than-55mb-fail-with-https-but-not-http?forum=windowsazuredata
See Rob Donovan's answer.

**Comment by yaqiyang** [comment]
This has been fixed by https://github.com/Azure/azure-sdk-for-php/pull/787. Please verify it using the newest dev-master code. Re-open the issue if you still see problems. 

thanks
Yaqi
