### ISSUE TITLE
$entity->getProperty("email")->getEdmType() does not work when type is String

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-sdk-for-php#756]
getEdmType() work on all other types -- other than string.

Consider the code:

    $filter = "email eq 'ksaye@saye.org'";

    try {
        $result = $tableRestProxy->queryEntities($tableName, $filter);
    }
    catch(ServiceException $e){
        $code = $e->getCode();
        $error_message = $e->getMessage();
        echo $code.": ".$error_message."<br />";
    }

    $entities = $result->getEntities();
    
        foreach($entities as $entity){
            echo "lastSeen = " . $entity->getProperty("email")->getValue() . "<br>";
            echo "type = '" . $entity->getProperty("email")->getEdmType() . "'<br>";

It returns a null string, yet if I try the code against a property that is other than string, say Int, DateTime or Boolean, it returns the appropriate information, such as: Edm.DateTime

Sample code and documentation attached:
[PHP SDK does not return string when using getEdmType.docx](https://github.com/Azure/azure-sdk-for-php/files/34211/PHP.SDK.does.not.return.string.when.using.getEdmType.docx)

**Comment by yaqiyang** [comment]
Null is being returned from the server when the type is string. As in http://azure.github.io/azure-sdk-for-java/com/microsoft/azure/storage/table/EdmType.html, null type will be matched to string. I will submit a PR to fix this in the coming days.
