### ISSUE TITLE
mimePart.php PEAR problem

### ISSUE THREAD

**Issue by joseforland** [Azure/azure-sdk-for-php#767]
Currently using the following composer settings to include azure-sdk-for-php

```javascript```
"require": {
    "cakephp/cakephp": "2.5.*",
    "recaptcha/php5": "v1.1.0",
    "microsoft/windowsazure": "*"
},      
"repositories": [
{
    "type": "pear",
    "url": "http://pear.php.net"
}
],
"minimum-stability": "dev"
```

I get the following error:

```
Missing argument 1 for Mail_mimePart::Mail_mimePart(), called in Vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/BatchRequest.php on line 106 and defined [/Vendor/pear/mail_mime-decode/Mail/mimePart.php]
```

The Mail_mimePart class in v1.5.5.2 (which is being installed according to the composer.json of microsoft/windowsazure) has the first parameter as required, not optional

Anyone can replicate this problem?

**Comment by joseforland** [comment]
after some further investigations I found that the pear/mail_mime & pear/mail_mime-decode has the same class, i.e. Mail/mimePart.php (Mail_mimePart)

in 1.5.5 the pear/mail_mime-decode was not in a folder Mail/ and once i forced that version in my composer.json, the error is gone

```javascript
"require": {
        "cakephp/cakephp": "2.5.*",
        "recaptcha/php5": "v1.1.0",
        "microsoft/windowsazure": "*",
        "pear/mail_mime-decode": "1.5.5"
    }
````

**Comment by yaqiyang** [comment]
This should have been fixed. Please re-open this issue if not fixed. 

Thanks
Yaqi
