### ISSUE TITLE
[RFC] Ensure update and consistency of `composer.lock` when `composer.json` is updated

### ISSUE THREAD

**Issue by phansys** [Azure/azure-sdk-for-php#770]
Since this repo keeps a `composer.lock` file with the resolved constraints for each requirement (and a hash validation for the contents of `composer.json`), is strictly mandatory to update this file alongside with `composer.json`; otherwise it leads to situations where the install process becomes unusable (except if you execute `update` instead `install`, but obviously that hasn't any sense when you're providing locked versions).
By instance, the PR #764 is merged into master with updates to `composer.json` but without any change to `composer.lock`; and now we have a problem:

```
$ composer update --lock
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear/net_url2 == 2.2.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by yaqiyang** [comment]
Thanks. We will try to keep them in sync
