### ISSUE TITLE
[RFC] Ensure only one commit by PR in order to keep the repo history clean

### ISSUE THREAD

**Issue by phansys** [Azure/azure-sdk-for-php#771]
In order to keep the repo history clean and readable, each PR should be restricted to just one fix or fixes related to the very same issue, without mixing concerns; and obviously the same should apply to new features.
During the lifecycle of code review, is OK to have many commits addressing comments, suggests, etc: but when the PR is ready to merge these commits should be squashed to a single one, which would have a concise and clear message about the proposed changes.
IMHO, the current output of `git log` is badly sad.

**Comment by yaqiyang** [comment]
Thanks for the suggestion. That is what we are trying to promote, too. 

Yaqi
