### ISSUE TITLE
CORS management support is missing

### ISSUE THREAD

**Issue by dkarlovi** [Azure/azure-sdk-for-php#777]
Currently there is not way to manage [CORS](http://blogs.msdn.com/b/windowsazurestorage/archive/2014/02/03/windows-azure-storage-introducing-cors.aspx)-related properties in (blob) service properties.

**Comment by yaqiyang** [comment]
Thanks for the suggestion. I will evaluate it

yaqi

**Comment by dkarlovi** [comment]
Hi @yaqiyang, thank you for your feedback, but I feel like the strategy of closing issues without a concrete action behind it might lead to a lot of issues being closed, but no progress made.

**Comment by jamesryan83** [comment]
I would like this feature too.  I need to load images from blob storage into a html canvas

**Comment by katmsft** [comment]
@dkarlovi @jamesryan83 
Cors management support is added in the 0.14.0 release of azure-storage-php repo. Check it out [here](https://github.com/Azure/azure-storage-php)
