### ISSUE TITLE
Problem when attemting to update a blob's properties

### ISSUE THREAD

**Issue by julesbl** [Azure/azure-sdk-for-php#778]
Got this problem when trying to update a set of blobs properties

			$blob_list = $this->cdn->cdn->listBlobs("assets");
			$blobs = $blob_list->getBlobs();
			$options = new WindowsAzure\Blob\Models\CreateBlobOptions();
			foreach($blobs as $blob)
			{
				$mime_type = get_mime_by_extension($blob->getName());
				echo $blob->getName().": ".$blob->getUrl(). ' : '.$mime_type. "<br />";
				$options->setBlobContentType($mime_type);
				echo 'setting';
				$this->cdn->cdn->setBlobProperties("assets", $blob->getName(), $options);
			}
		} catch (WindowsAzure\Common\ServiceException $ex) {
			echo $ex->getCode(). ': '. $ex->getMessage();
		}

produces the following error

Fatal error: Call to undefined method WindowsAzure\Blob\Models\CreateBlobOptions::getBlobContentLength() in /var/www/vendor/microsoft/windowsazure/WindowsAzure/Blob/BlobRestProxy.php on line 1922
A PHP Error was encountered

Severity: Error

Message: Call to undefined method WindowsAzure\Blob\Models\CreateBlobOptions::getBlobContentLength()

Filename: Blob/BlobRestProxy.php

Line Number: 1922

Backtrace:

**Comment by devigned** [comment]
Sorry you ran into this. We'll take a look at this.

**Comment by yaqiyang** [comment]
Confirmed. CreateBlobOptions::getBlobContentLength() is not defined. Will include a fix in the upcoming release.

Yaqi
