### ISSUE TITLE
PHP 5.3 compatibility issues

### ISSUE THREAD

**Issue by konstantin-komelin** [Azure/azure-sdk-for-php#779]
Hi there,

**SDK Version:** 0.4.0

I've just got the following error:
```
syntax error, unexpected '[', expecting ')'
in
microsoft/windowsazure/WindowsAzure/MediaServices/MediaServicesRestProxy.php:2879
```
I'm using PHP 5.3 but the code needs at least 5.4 because it uses short syntax for arrays which was introduced just in PHP 5.4 http://php.net/manual/en/migration54.new-features.php

I encourage you to update the README accordingly or test compatibility with PHP 5.3 and provide some fixes.
Also, please update the text "**You must have PHP 5.3 or higher to use the PHP client libraries for Azure.**"  on https://azure.microsoft.com/en-gb/documentation/articles/php-download-sdk/ 

Thanks,
Konstantin

**Comment by konstantin-komelin** [comment]
I'll tell you why I'm asking. I've just got the following error:
```
syntax error, unexpected '[', expecting ')'
in
microsoft/windowsazure/WindowsAzure/MediaServices/MediaServicesRestProxy.php:2879
```
I'm using php 5.3 but your code needs at least 5.4 because it has short syntax for arrays which was introduced just in php 5.4 http://php.net/manual/en/migration54.new-features.php

I encourage you to update README accordingly or test compatibility with PHP 5.3 and provide some fixes.
Also, please update the text:
**You must have PHP 5.3 or higher to use the PHP client libraries for Azure.**  
on https://azure.microsoft.com/en-gb/documentation/articles/php-download-sdk/ 

Thanks,
Konstantin

**Comment by konstantin-komelin** [comment]
Working on the pull request.

**Comment by yaqiyang** [comment]
@konstantin-komelin, from the other thread, I have rejected your pull request to support 5.3. I am in the process of updating readme and other files to require PHP 5.4 and above, but under 7.0. Let me know if you have other questions.
Thanks for your contribution. 
Yaqi Yang
