### ISSUE TITLE
How to create table if it doesn't exist

### ISSUE THREAD

**Issue by dczaretsky** [Azure/azure-sdk-for-php#781]
I must be missing something, but I'm having trouble creating a table if it doesn't exist. The documentation is pretty poor, but from what I can tell calling createTable() will throw an exception if the table already exists. My assumption was to do a getTable() and if it returns null, then create the table. However, calling getTable() when the table doesn't exist also throws an exception. It seems to be a bug. 

Here's my code, if someone can provide some insight as to what is wrong with this approach, or how to  get around this bug:

```
    $connection_string = 'DefaultEndpointsProtocol=https;AccountName=' . $account_name . ';AccountKey=' . $account_key;
    $tableRestProxy = ServicesBuilder::getInstance()->createTableService($connection_string);
    $table = 'mytable';

    try {
        if ( !$tableRestProxy->getTable($table) )   // exception is thrown when getTable is called
        {
            $tableRestProxy->createTable($table);
        }
    }
    catch(ServiceException $e) {
        $code = $e->getCode();
        $error_message = $e->getMessage();
        return;
    }
```

**Comment by dczaretsky** [comment]
FYI, here is the exception that is thrown when calling getTable():

WindowsAzure\Common\ServiceException: Fail: Code: 404 Value: Not Found details (if any): <?xml version="1.0" encoding="utf-8"?><error xmlns="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><code>ResourceNotFound</code><message xml:lang="en-US">The specified resource does not exist. RequestId:745094c9-0002-0009-0fce-7baecf000000 Time:2016-03-11T19:46:49.6064944Z</message></error>. in WindowsAzure\Common\Internal\Http\HttpClient::throwIfError() (line 382 of /lib/WindowsAzure/Common/Internal/Http/HttpClient.php).

**Comment by yaqiyang** [comment]
That is the expected behavior when you call getTable. You can call queryTables() with a filter in the options parameter to check if the table exists, or just catch the exception from getTable(). If the exception is “resource does not exist”, the table does not exist.

Hope that helps.
Yaqi Yang

**Comment by dczaretsky** [comment]
Thanks Yaqi. That's really not a very intuitive UI. There's a great deal of difference between errors and exceptions, the latter typically killing your application.  I spent 3 days trying to debug the API because of lack of documentation. Maybe consider rethinking how the API should return "not found" errors. Or provide some more intuitive helper functions that do the job for you.

To get around it, I've created a helper function that returns true if it exists, in case anyone else encounters this same problem.

```
function tableExists($tableRestProxy, $table) 
{
    if ( !isset($tableRestProxy) || empty($tableRestProxy) ||
         !isset($table) || empty($table) )
    {
        return FALSE;
    }

    try {
        $tableRestProxy->getTable($table);
        return TRUE;
    }
    catch (ServiceException $e)
    {
        return FALSE;
    }
}
```

**Comment by yaqiyang** [comment]
getTable() returns GetTableResult which essentially is the name of the table. To have it return an error instead of throwing an exception is possible but will break the pattern of such functions. queryTable() should be used in such situations.
