### ISSUE TITLE
[RFC] Adopt PSR-2 as basic coding standard

### ISSUE THREAD

**Issue by phansys** [Azure/azure-sdk-for-php#793]
This is a RFC created to propose and debate about [PSR-2](http://www.php-fig.org/psr/psr-2/) as coding standard base.

**Comment by yaqiyang** [comment]
Thanks for this info. I will take a look and also review your PR. 

Yaqi

**Comment by yaqiyang** [comment]
@phansys , can you close this issue? 
Thanks
Yaqi

**Comment by phansys** [comment]
Closing this since #794 is merged. `php-cs-fixer` must be configured at CI suite in order to ensure proper CS.
