### ISSUE TITLE
Removal of PEAR packages such as http_request2

### ISSUE THREAD

**Issue by yaqiyang** [Azure/azure-sdk-for-php#797]
I am opening a new issue to track this since we are hearing many request to replace PEAR package by alternatives such as Guzzle.

**Comment by yaqiyang** [comment]
This is related to https://github.com/Azure/azure-sdk-for-php/issues/747, and also should take care of https://github.com/Azure/azure-sdk-for-php/issues/758, and maybe https://github.com/Azure/azure-sdk-for-php/issues/733

**Comment by atrauzzi** [comment]
Be sure to use the current version of guzzle.

**Comment by yaqiyang** [comment]
@sergey-shandar, please take a look at this

**Comment by sergey-shandar** [comment]
- "pear/http_request2": "^2.3", 
- "pear/net_url2": "^2.2", 
- "pear/mail_mime": "^1.10", 
- "pear/mail_mime-decode": "^1.5",

**Comment by sergey-shandar** [comment]
See also #906 and #907.
