### ISSUE TITLE
Container name with incorrect <space> causes Mac Validation error

### ISSUE THREAD

**Issue by lukos** [Azure/azure-sdk-for-php#798]
I incorrectly tried to call listBlobs with a container name that had a space in it "uploaded files" instead of "uploadedfiles", which is an illegal name. I would have expected a straight-forward exception to be thrown but instead, was shown the dreaded: **The MAC signature found in the HTTP request ... is not the same as any computed signature.**

This took me hours to fix because it looked like a much more serious error than it really was (did I need to manually compute the signature etc.).

I guess that any API call that requires a conforming name to be passed for container or blob name should validate the format in the SDK and throw an exception rather than pass the call to the API. It would also be nice if the API itself returned a more useful error but that is someone else's problem.

**Comment by katmsft** [comment]
@lukos 
Please see [this](https://github.com/Azure/azure-storage-php/issues/4) for latest update, thanks!
