### ISSUE TITLE
Package not being updated on Packagist

### ISSUE THREAD

**Issue by Sazpaimon** [Azure/azure-sdk-for-php#808]
The last commit of dev-master for `microsoft/windowsazure` on Packagist is from `2016-03-17 00:04 UTC`. Is it possible that the commit hooks aren't working anymore?

**Comment by devigned** [comment]
I think we should be good now. Check out the version: https://packagist.org/packages/microsoft/windowsazure#dev-master.

**Comment by phansys** [comment]
Excellent: `dev-master / 0.4.x-dev 2016-04-08 00:29 UTC`.

**Comment by yaqiyang** [comment]
@Sazpaimon , can you close if it does not happen anymore?

Thanks
yaqi

**Comment by Sazpaimon** [comment]
Yep, looks like it's working now. Thanks!
