### ISSUE TITLE
How to get Container and Blob Properties and size

### ISSUE THREAD

**Issue by babatundeOS** [Azure/azure-sdk-for-php#812]
how can I get the properties of a container? Eg size, date created, modified etc.
Any way out on this?

**Comment by yaqiyang** [comment]
Here is some sample code to get container properties. At the time, we are not getting back all properties,


    $blobRestProxy = ServicesBuilder::getInstance()->createBlobService($connectionString);
    $containerlist = $blobRestProxy->listContainers();
    $containers = $containerlist->getcontainers();

    echo "<h2>Existing Containers:</h2>";
    echo "<table>";
    echo "<tr><th>Name</th>";
    echo "<th>Url</th>";
    echo "<th>Last Modified</th>";
    echo "<th>Etag</th>";
    echo "</tr>";    

    foreach($containers as $container) {
        $props = $container->getProperties();
        echo "<tr><td>".$container->getName()."</td>";
        echo "<td>".$container->getUrl()."</td>";
        echo "<td>".$props->getLastModified()->format('Y-m-d H:i:s') ."</td>";
        echo "<td>".$props->getETag()."</td>";
        echo "</tr>";        
    }
    echo "</table>";

**Comment by babatundeOS** [comment]
Hi @yaqiyang  

Thanks for your response. Can I get the size of the container? The most important property for me now is the size of each container, folder, blob.

Thanks

**Comment by yaqiyang** [comment]
I think the size is calculated. If you go to https://msdn.microsoft.com/en-us/library/azure/dd179370.aspx, you can see all container properties. Size is not one of the container properties.

**Comment by babatundeOS** [comment]
First, I tried the example given in that link but didnt work.
Second, since size is not one of container properties, is there another way to get the **size**? This is really important for what I'm working on.

Thanks @yaqiyang

**Comment by yaqiyang** [comment]
You need to aggregate all blobs in the container, see http://stackoverflow.com/questions/14376459/azure-storage-container-size. There is no API for that yet, as far as I know

**Comment by babatundeOS** [comment]
The example there is for `C#`. I dont seem to find any reference to where or how to do this with ***`php`***. Is it possible with *php*?

**Comment by yaqiyang** [comment]
Yes, it is a C# example. All SDK languages wrap the same REST API on Azure. Basically it shows the size property does not exist and can only be obtained by listing all blobs in the container and then sum them up. Hope this helps.

**Comment by babatundeOS** [comment]
@yaqiyang  I understand what the C# example does; summing up all blobs sizes in a container. The problem here is that I cant find the equivalent of getting blobs sizes in azure sdk for php.
`size += blob.Properties.Length;` - what's the equivalent to that in php?

I tried to iterate through `$blob->getProperties()` but it's empty. Nothing is returned.

Also tried `filesize($blob->getUrl())` but gave error. Please help on this.

**Comment by yaqiyang** [comment]
$props = $blob->getProperties();
$size = $props->getContentLength();

If this does not work, I will try to get some working code tomorrow.

**Comment by babatundeOS** [comment]
@yaqiyang No, it doesn't work. I'd be expecting your working code.

Thanks.

**Comment by yaqiyang** [comment]
try this,

    //blob tests     
    $blobRestProxy = ServicesBuilder::getInstance()->createBlobService($connectionString);
    $testcontainername = 'phpcontainer1';

    echo "<h2>Existing Blobs:</h2>";
    echo "<table>";
    echo "<tr><th>Name</th>";
    echo "<th>Last Modified</th>";
    echo "<th>Size</th>";
    echo "</tr>";   

    try 
    {
        $blob_list = $blobRestProxy->listBlobs($testcontainername);
        $blobs = $blob_list->getBlobs();

        foreach($blobs as $blob)
        {
            $propResult = $blobRestProxy->getBlobProperties($testcontainername, $blob->getName(), null);

            echo "<tr><td>" . $blob->getName() ." </td>";
            echo "<td>" . $propResult->getProperties()->getLastModified()->format('Y-m-d H:i:s') . "</td>";
            echo "<td>" . $propResult->getProperties()->getContentLength() . "</td>";
            echo "</tr>";
        }
    }
    catch(ServiceException $e)
    {
        $code = $e->getCode();
        $error_message = $e->getMessage();
        echo $code.": ".$error_message."<br />";
    }

**Comment by babatundeOS** [comment]
Great! This works. Thanks a lot @yaqiyang

**Comment by YunLi1988** [comment]
the blob from Container.GetBlockBlobReference have blob.Properties.Length as -1. Is it a bug?

**Comment by Chettra7** [comment]
How to get file image to view?
