### ISSUE TITLE
[RFC] Remove `build` dir + add dev dependencies for configured tools

### ISSUE THREAD

**Issue by phansys** [Azure/azure-sdk-for-php#813]
With this issue I'm proposing to remove the `build` directory, which currently ships scripts that aren't required anymore (`src_autoload.php.in`, `tests_autoload.php.in`).
Configuration files such as `phpcs.xml` and `phpmd.xml` should be moved to the root directory and dev requirements should be added to `composer.json` in order to integrate the tools capable to use these files (I guess they are PHP CodeSniffer and PHP Mess Detector).

**Comment by yaqiyang** [comment]
Why do you want to remove my release_tools.php?

**Comment by phansys** [comment]
IMO, that file don't seems to be part of this project: It is a scaffolder-like script to patch files of this library. BTW, I can revert the remove and place it under project's root if you have some concerns about it.

**Comment by yaqiyang** [comment]
It is a just build utility. I think it should be under build

**Comment by phansys** [comment]
It will be left alone since the other files were moved, but the discussion for it can be done later. I haven't strong concerns about it at this time.

**Comment by phansys** [comment]
Closing since #814 is merged.

**Comment by yaqiyang** [comment]
Thanks a lot for your contribution!
