### ISSUE TITLE
[RFC] Remove `deprecated` dir and handle deprecations through versions instead locations

### ISSUE THREAD

**Issue by phansys** [Azure/azure-sdk-for-php#815]
Deprecations and code removal should be done in a clearer way, advising about the removal in previous versions via `trigger_error('Deprecation message', E_USER_DEPRECATED)` and `@deprecated` docblocks, removing the code in the corresponding version.
Moving code to another location (such as [`deprecated`](https://github.com/Azure/azure-sdk-for-php/tree/1f73f6cbedd367a88dd81dab639acb275b21f742/deprecated)) does not seem a proper deprecation path when the library can take advantage of versioning basic concepts.

**Comment by yaqiyang** [comment]
The files in the deprecated folder is for PEAR package manager. It is not part of the source code. I will just remove that folder after release 0.4.2 is out.

**Comment by yaqiyang** [comment]
This should be closed. I have submitted the PR
