### ISSUE TITLE
MPE_ENC_ENCRYPTION_REQUIRED

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-sdk-for-php#819]
Hi,

I would like to ask you about playing ism file after successfully upload video to azure media service. Why I cannot play it ? this is the error: 

`<?xml version="1.0" encoding="UTF-8"?>

-<serverError>

<status>403</status>

<subStatus>0</subStatus>

<hresult>MPE_ENC_ENCRYPTION_REQUIRED</hresult>

<activityId>80003ADA-0000-FB00-B63F-84710C7967BB</activityId>

<serviceId>1B41F4FC-2747-03C0-37B9-3B23DD250366</serviceId>

</serverError>`

**Comment by yaqiyang** [comment]
Where are you trying to play it from? What OS?

**Comment by adityosnrost** [comment]
Hi @yaqiyang ,

I'm trying to play it directly on EGDE browser. I am using Windows 10 Pro. EGDE has direct ism player, I can play some ism file on it with other URL.

Thank You

**Comment by yaqiyang** [comment]
https://azure.microsoft.com/en-us/documentation/articles/media-services-encode-asset/
It does not seem ISM is supported. I am not familiar with streaming, but I don't think you can play it directly from your browser. When your encoding is done, you get some access keys. You will need to use them somehow to access the content, not directly from the browser.

**Comment by adityosnrost** [comment]
@yaqiyang ,

Sorry for my late reply, I was working on other issue. I know why I cannot play it, because it is AES encrypted haha, I forgot that I need to use AES also on my media player. 

I would like to know if I want to store audio file using same file, what presets that I should use ?
Video = H264 Multiple Bitrate 720p
Audio = ?

Thanks
