### ISSUE TITLE
PUBLIC NOTICE: Repository and package changes

### ISSUE THREAD

**Issue by nowenL** [Azure/azure-sdk-for-php#821]
To better serve our user community with support for newer service features, the Azure Storage team is working on moving the Storage APIs within azure-sdk-for-php into a [new repository](https://github.com/Azure/azure-storage-php).

The first release [v0.10.0](https://github.com/Azure/azure-storage-php/releases/tag/v0.10.0) is available now and includes changes to replace all Pear dependencies with [Guzzle](https://github.com/guzzle/guzzle). We encourage you to move to the new library for faster issue resolution and quicker feature implementation. This release shares mostly the same interfaces as Storage Blobs, Tables and Queues in Azure SDK for PHP v0.4.1. However, there are some minor breaking changes need to be addressed during migration. You can find the details in BreakingChanges.md.

Following this, we plan to update the library to add support for newer service features including SAS support, append blob and file service.

Please note that this new library is still in preview and may contain breaking changes in upcoming releases. We look forward towards your feedback and partnership.

Thanks,
Azure Storage Team

**Comment by Sazpaimon** [comment]
> The first release v0.10.0 is available now and includes changes to replace all Pear dependencies with Guzzle

Thank you thank you thank you!
