### ISSUE TITLE
Encoding consumes more time than uploading

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-sdk-for-php#825]
Hi,

I'm using php sdk to upload a video into my azure media service. I would like to know why encoding consumes more time than uploading ?

Upload consumes 1 - 3 seconds for 3 mb video.

Encoding consumes  1 and half minute for 3 mb video.

Thanks

**Comment by yaqiyang** [comment]
The encoded file usually is much larger than the original. Apparently there is a lot of work there.

**Comment by yaqiyang** [comment]
@adityosnrost , can you close this issue? It does not seem to be an issue with the SDK.

Thanks
Yaqi

**Comment by adityosnrost** [comment]
@yaqiyang , thanks for your help, sorry for late reply hehe.
