### ISSUE TITLE
Storage API Issue

### ISSUE THREAD

**Issue by olsgreen** [Azure/azure-sdk-for-php#826]
I've bee trying to upload to a container and constantly receiving:

    ServiceException {#298
      -_error: "The value for one of the HTTP headers is not in the correct format."
      -_reason: ""
      #message: """
        Fail:\n
        Code: 400\n
        Value: The value for one of the HTTP headers is not in the correct format.\n
        details (if any): .
        """
      #code: 400
      #file: "/../vendor/microsoft/windowsazure/WindowsAzure/Common/Internal/Http/HttpClient.php"
      #line: 383

With a bit of googling I found this:

https://github.com/Azure/azure-sdk-for-python/issues/288#issuecomment-74399273

I changed '2012-02-12' to '2014-02-14' here... https://github.com/Azure/azure-sdk-for-php/blob/master/WindowsAzure/Common/Internal/Resources.php#L251

Works without a problem. Are you referencing an old version of the api?

**Comment by yaqiyang** [comment]
yes, the SDK here is using an older version of the API. The storage API has been replaced by https://github.com/Azure/azure-storage-php which is using the newest version.

yaqi

**Comment by olsgreen** [comment]
Righy ho... I shall migrate. Thanks.

**Comment by yaqiyang** [comment]
I just submitted a PR to replace the current storage API with the new Storage SDK. That should fix your issue. 

yaqi
