### ISSUE TITLE
MediaServices getAssetList() for large Asset Collections

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-sdk-for-php#835]
We have MediaServices Accounts with a few thousand active Assets - the current "getAssetList" function is not sufficient for this amount of assets.
To overcome this issue, we modified the function with a "skip" parameter:

```
public function getAssetsList($skip=0){
$propertyList=$this->_getEntityList("Assets()?"."$skip=".$skip);
...
}
```

This is probably not the most elegant version, but its working without any problems.
Maybe you can add a functionality like this for really large Asset Lists.

**Comment by yaqiyang** [comment]
Good idea. I will take a look when I get a chance. If you want to submit a PR, that will be good, too.

**Comment by yaqiyang** [comment]
@boredom2 , please take a look at PR https://github.com/Azure/azure-sdk-for-php/pull/836.

Thanks
Yaqi

**Comment by boredom2** [comment]
That looks indeed good and far better than the original proposal. Thanks a lot for that quick fix!

**Comment by yaqiyang** [comment]
The PR has been merged. Please close this issue if it works for you. Thanks a lot for your contribution!

Yaqi
