### ISSUE TITLE
InvalidHeaderValue with Flysystem in Laravel

### ISSUE THREAD

**Issue by stefanedberg** [Azure/azure-sdk-for-php#840]
Background:
https://github.com/thephpleague/flysystem/issues/647

As you can see updating STORAGE_API_LATEST_VERSION seems to solve the problem. Am I doing something wrong?

**Comment by yaqiyang** [comment]
If you get the newest build of PHP SDK v0.4.3, the storage API has been updated. The newest STORAGE_API_LATEST_VERSION is 2015-04-05. Please try it.

**Comment by stefanedberg** [comment]
Thanks for your reply y,

When I update microsoft/ Flysystem seem to crash:

Type error: Argument 1 passed to League\Flysystem\Azure\AzureAdapter::__construct() must be an instance of WindowsAzure\Blob\Internal\IBlob, instance of MicrosoftAzure\Storage\Blob\BlobRestProxy given

**Comment by yaqiyang** [comment]
It seems the Flysystem must be updated in order to use the new storage SDK. Can you contact its owner?

**Comment by yaqiyang** [comment]
Can this issue be closed?

**Comment by stefanedberg** [comment]
Yes, thank you yaqiyang.
