### ISSUE TITLE
v0.4.3 release notes don't mention ServiceException 

### ISSUE THREAD

**Issue by ScottHelme** [Azure/azure-sdk-for-php#841]
The release notes say that we have to change:

    "use WindowsAzure\Blob" to "use MicrosoftAzure\Storage\Blob", 
    "use WindowsAzure\Queue" to "use MicrosoftAzure\Storage\Queue"
    "use WindowsAzure\Table" to "use MicrosoftAzure\Storage\Table"

After deploying the changes to my test environment certain features stopped working. I had to make additional changes:

    "use WindowsAzure\Common\ServiceException" to "use MicrosoftAzure\Storage\Common\ServiceException"

I haven't encountered any other problems so that may be the only other change required.

**Comment by yaqiyang** [comment]
Thanks for finding that. I will update the notes.

**Comment by nowenL** [comment]
Hi, Yaqi. Please update for WindowsAzure\Common\ServicesBuilder as well. It should be changed to MicrosoftAzure\Storage\Common\ServicesBuilder if it's used for storage services.

**Comment by yaqiyang** [comment]
WindowsAzure\Common\ServicesBuilder.createBlobService() will return StorageServiceBuilder::getInstance()->createBlobService(). So there is no need to change to MicrosoftAzure\Storage\Common\ServicesBuilder in your code unless you are referencing something else in MicrosoftAzure\Storage\Common\ServicesBuilder class.

**Comment by nowenL** [comment]
Cool! Thanks yaqi.

**Comment by yaqiyang** [comment]
Close it. I updated the change log, https://github.com/Azure/azure-sdk-for-php/pull/843
