### ISSUE TITLE
URL Streaming

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-sdk-for-php#842]
Hi, I would like to know how to getting a URL streaming from Media Services without encoding the file first. for current example, the publishEncodedAsset function is looking for manifest file:

`// 6.1 Get the .ISM AssetFile
    $files = $restProxy->getAssetAssetFileList($encodedAsset);
    $manifestFile = null;

    foreach ($files as $file) {
        if (endsWith(strtolower($file->getName()), '.ism')) {
            $manifestFile = $file;
        }
    }

    if ($manifestFile == null) {
        echo "Unable to found the manifest file\r\n";
        exit(-1);
    }
`
Can I getting the URL based on original asset that I uploaded ?

**Comment by yaqiyang** [comment]
Sorry for the late reply. I will take a look at this problem on Tuesday.

**Comment by yaqiyang** [comment]
From https://azure.microsoft.com/en-us/documentation/articles/media-services-portal-get-started/, it does not seem you can get a streaming URL without encoding the file first. You cannot publish any media file unless it is encoded.

**Comment by adityosnrost** [comment]
Hi, thanks for your reply. I tried couple way on some settings and code to get some URL regarding to my assets. I found that uploaded file can be published by using locator(On Demand Origin, SAS) that provide some Progressive Download URL. Luckily, That I can used that on my player as streaming file. It is cost more than encoding files because it is using raw file to stream, but it is fine to me because later they will be encoded by my other script.

But, it led me to another problem. If I had another php script to encoding my uploaded files. Can I get a asset object by asset name ? Thanks

**Comment by yaqiyang** [comment]
asset names are not unique while Ids are. You can call MediaServicesRestProxy->getAssetList() and iterate through the list to find your asset.

**Comment by adityosnrost** [comment]
Hi, thanks for your reply. I found that I can use Asset id. is getAsset() method can be used like getAsset('AssedID') ? 

Thanks

**Comment by yaqiyang** [comment]
yes

**Comment by adityosnrost** [comment]
Thanks for your help, this is so helpful :D
