### ISSUE TITLE
Azure Storage for Wordpress Plugin in major need of love

### ISSUE THREAD

**Issue by GeoffreyEmery** [Azure/azure-sdk-for-php#845]
I know this team didn't writethis plugin, but in the end of the day its a php sdk implementation. In addition it kind of looks bad at the little love this is getting considering that wordpress powers about 1/3 of all sights on the internet. if your note the team to pick up this chllenge can  let me know who is? 
This is the plugin : https://wordpress.org/plugins/windows-azure-storage/
I believe MS has folded the main open source team back into the other teams and the next option is the vendor who is clearly not responsive. There are several people willing to make updates to it but there is no way to do this in the current form. 
My main issue was that it doesn't replace the buddy press avatars or the profile background pictures just the media libraries.

**Comment by devigned** [comment]
Thank you for bringing this up. I'm going to look into who from MSOT owned this previously and see what we can do to improve the situation. I'll ping back.

**Comment by lukdanek** [comment]
Appreciated this! We would need working version of this plugin too.

**Comment by devigned** [comment]
Quick update: found out who owned up keep of the plugin last. I'm now figuring out who will be updating it going forward.

**Comment by GeoffreyEmery** [comment]
Here are list of all the azure plugins for wordpress currently floating around. Some are not MS but should give you some ideas of how people have tried to make this work by developing their own solutions. Thought it might help. https://wordpress.org/plugins/tags/windows-azure , https://wordpress.org/plugins/tags/azure

**Comment by CedricMi** [comment]
Can we please get an update on the future, or lack of future, of Azure Storage for Wordpress Plugin ?

**Comment by PaulHale** [comment]
+1 for an update please!

**Comment by devigned** [comment]
@kamaljit and @yaqiyang please give this a look when you have a moment.

**Comment by sergey-shandar** [comment]
I'm going to investigate the issue in November.

**Comment by skip405** [comment]
Hi everyone, bringing this up again, the plugin does get some attention from time to time, yes. Can we ask for it to be open-sourced here on Github, so that any interested person could create a pull-request?

For example, the feature I currently lack in this plugin is CacheControl, which I'm willing to try and do. I see this option is available in code, but it's not available on the settings page and it's not sent to Azure.

**Comment by sergey-shandar** [comment]
As far as I understood, the plugin is already open-sourced https://github.com/10up/windows-azure-storage and maintained by the 10up team. Please, contact them directly.

**Comment by sergey-shandar** [comment]
I created the issue there https://github.com/10up/windows-azure-storage/issues/14 to keep track for this discussion. I'm going to close this one.
