### ISSUE TITLE
media service content protection

### ISSUE THREAD

**Issue by speed1speed1** [Azure/azure-sdk-for-php#850]
Dose any way to use this sdk protect my livestream content one token one user?
Because maybe they copy token.
Thanks.

**Comment by yaqiyang** [comment]
Tokens will expire in sometime after being issue. I don't have any real token for Media Services right now, so I don't know exactly how long it lasts before expiration. What is your real concern here? Is your token accessible by other people?

**Comment by speed1speed1** [comment]
Yes, token is working during the expiration.
So if them copy and paste.
Our payment mechanism will fail.

**Comment by yaqiyang** [comment]
The token is only known to your application which should protect it before it expires. It should not be shared with other applications or accessible by other people.

**Comment by speed1speed1** [comment]
My client is a web application and used azure media player.
Azure media player put the token in html or javascript.
I got token from php server and put it to azure media player.
Client can see the token in any web debug mode.
Maybe I only can set the expiration to 10s?

**Comment by yaqiyang** [comment]
How exactly did you get the token? By calling OAuthestProxy or TokenRestrictionTemplateSerializer or other means? TokenRestrictionTemplateSerializer has an option to set expiration. If you are using that, you can set it to 10 seconds.

**Comment by yaqiyang** [comment]
https://azure.microsoft.com/en-us/documentation/articles/media-services-dotnet-configure-content-key-auth-policy/. This might help, especially the **Token Restriction** section. But still, it does not seem you can fully secure the token.

**Comment by speed1speed1** [comment]
I am using TokenRestrictionTemplateSerializer.
It looks only set the expiration.
Thank you very much.

**Comment by yaqiyang** [comment]
I am closing this issue. Please open a new issue if you have further questions on the PHP SDK. Thanks for using our SDK!
