### ISSUE TITLE
Ingest Asset

### ISSUE THREAD

**Issue by adityosnrost** [Azure/azure-sdk-for-php#860]
Hi, I would like to know how Ingest Asset workflow on this sdk ?

Thank You

**Comment by yaqiyang** [comment]
You can find some info at https://azure.microsoft.com/en-us/documentation/articles/media-services-overview/. Let me know if that answers your question.

**Comment by rnrneverdies** [comment]
Hi @adityosnrost,

In [this](https://github.com/Azure/azure-sdk-for-php/tree/master/examples/MediaServices) folder, you can find some VOD workflow PHP samples showing how to:
- create & ingest assets 
- encode assets
- apply content protection (each sample uses a differnt content protection method) 
- publish encoded assets

Aditionally, in [this](http://southworks.com/blog/2016/08/22/new-microsoft-azure-media-services-sdks-for-java-and-php-release-with-fairplay-streaming-support/) blog post you can find some additional information about importing dependencies via Composer.

Are you asking about a particular ingest method? If you are interested, we could prepare a sample about bulk ingest with IngestManifest?

Hope it helps!
Emanuel

**Comment by adityosnrost** [comment]
Hi @yaqiyang and @rnrneverdies ,

Thanks for your reply. I have read the documentation and also samples. I would like to create automation like this https://github.com/liarjo/MediaBlutlerTest01 or the same automation for what brightcove has with the same name (ingest). So, Azure Media Services can automatically grab any new media that has not been encoded yet to be process and auto publish them.

I have some custom request to do an automation included with reporting process. I would like to create it with all features that provided by the SDK?

Thank You

Best Regards,

Adityo

**Comment by yaqiyang** [comment]
The SDK provides methods for encoding and publishing. For your purpose, you need to use PHP to create a listener or daemon to monitor the media files at a certain location and then use the SDK to encode and publish them. Does that answer your question?

**Comment by adityosnrost** [comment]
Thanks for your suggestion. I'll try to build it.
