### ISSUE TITLE
Need to make sure all calls have the correct UserAgent

### ISSUE THREAD

**Issue by yaqiyang** [Azure/azure-sdk-for-php#866]

**Comment by sergey-shandar** [comment]
A list of tests that sends HTTP(S) requests:

- Tests that require HTTP connection:
  - tests/unit/WindowsAzure/Common/Internal/Http/HttpClientTest.php
- Tests that require AZURE_STORAGE_CONNECTION_STRING
  - tests/unit/WindowsAzure/Common/Internal/Authentication/OAuthSchemeTest.php
  - tests/unit/WindowsAzure/Common/Internal/Filters/WrapFilterTest.php
  - tests/unit/WindowsAzure/Common/Internal/OAuthRestProxyTest.php
  - tests/unit/WindowsAzure/Common/ServicesBuilderTest.php
  - tests/unit/WindowsAzure/MediaServices/MediaServicesRestProxyTest.php
  - tests/unit/WindowsAzure/MediaServices/MediaServicesRestProxyTest.php
  - tests/unit/WindowsAzure/ServiceBus/Internal/WrapTokenManagerTest.php
  - tests/unit/WindowsAzure/ServiceBus/ServiceBusRestProxyTest.php
  - tests/unit/WindowsAzure/ServiceBus/WrapRestProxyTest.php
  - tests/unit/WindowsAzure/ServiceManagement/ServiceManagementRestProxyTest.php

**Comment by sergey-shandar** [comment]
[A definition of SDK_USER_AGENT](https://github.com/Azure/azure-sdk-for-php/blob/master/src/Common/Internal/Resources.php#L254).
