### ISSUE TITLE
Investigate and fix failing tests

### ISSUE THREAD

**Issue by yaqiyang** [Azure/azure-sdk-for-php#868]

**Comment by sergey-shandar** [comment]
All failing tests in [MediaServicesRestProxyTest.php](https://github.com/Azure/azure-sdk-for-php/blob/master/tests/unit/WindowsAzure/MediaServices/MediaServicesRestProxyTest.php):

1. Tests\unit\WindowsAzure\MediaServices\MediaServicesRestProxyTest::testGetAssetList
Failed asserting that actual size 48 matches expected size 1.
2. Tests\unit\WindowsAzure\MediaServices\MediaServicesRestProxyTest::testGetLocatorList
Failed asserting that actual size 23 matches expected size 1.
3. Tests\unit\WindowsAzure\MediaServices\MediaServicesRestProxyTest::testGetJobTemplateList
Failed asserting that 6 matches expected 1.
4. Tests\unit\WindowsAzure\MediaServices\MediaServicesRestProxyTest::testGetTaskTemplateList
Failed asserting that 6 matches expected 1.

**Comment by sergey-shandar** [comment]
It works for me. So, it looks like a problem with @yaqiyang machine/account.
