### ISSUE TITLE
Azure Storage Library

### ISSUE THREAD

**Issue by boredom2** [Azure/azure-sdk-for-php#913]
Hi there,

is there any Reason, why the Composer still uses the 0.10 Version of the Azure Storage Library?
They just upgraded to 0.12 with interesting new Features and it would be interesting to know, if this could be updated easily? Or do you see any deeper Problems and stay at 0.10 for that reason?

Thanks!

**Comment by sergey-shandar** [comment]
@boredom2 no, there's no problem. There's no changes in Azure SDK itself so we didn't plan to update it yet.

**Comment by sergey-shandar** [comment]
It should be resolved in 0.5.2 and 0.5.3
