### ISSUE TITLE
Create an asset from a existing blob

### ISSUE THREAD

**Issue by cassianotartari** [Azure/azure-sdk-for-php#915]
Hi!

I'm trying to figure out how to create an asset to streaming using an already uploaded video to blob storage. The storage is the same used in media services.

I've tried to use ``Iblob::copyBlob`` but it seems to not accept the asset as destination.

Now I'm thinking in use ``Iblob::getBlob`` to get file content and ``MediaServicesRestProxy::uploadAssetFile`` to set this content to my assetFile.

Is this the way?

Thanks.

**Comment by sergey-shandar** [comment]
@cassianotartari This question is related to Azure Storage for PH: https://github.com/Azure/azure-storage-php

**Comment by cassianotartari** [comment]
ok... but is kind of related to this repository because of the asset creation.
