### ISSUE TITLE
Mcrypt deprecated on php 7.1

### ISSUE THREAD

**Issue by nspd** [Azure/azure-sdk-for-php#918]
mcrypt_encrypt is deprecated on php 7.1 and it's suggested to use openssl_encrypt.
http://php.net/manual/en/migration71.deprecated.php

In the file /src/MediaServices/Models/ContentKey.php lines 405~410 it's used this method.

         $encrypted = mcrypt_encrypt(
            MCRYPT_RIJNDAEL_128, // AES
            $aesKey,
            $this->_id,
            MCRYPT_MODE_ECB
        );

**Comment by boredom2** [comment]
I just would like no emphasize, that today, PHP 7.2 has been released and MCRYPT is now removed from the PHP Core. It would really be great, if this code could get re-designed.
