### ISSUE TITLE
listBlobsOptions has been removed ?

### ISSUE THREAD

**Issue by rangarajan-k** [Azure/azure-sdk-for-php#930]
I am trying to get blob with a specific prefix. But i am not able to execute the function. here is the code
`$blobListOptions = new ListBlobsOptions();
$blobListOptions->setPrefix('test/');
$blob_list = $blobRestProxy->listBlobs($container_name,$blobListOptions);`

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-storage-php

**Comment by sergey-shandar** [comment]
https://github.com/Azure/azure-storage-php/issues/90

**Comment by katmsft** [comment]
@rangarajan-k Could you please also provide the output of the error?
