### ISSUE TITLE
Header field-name capitalization is not controlable

### ISSUE THREAD

**Issue by jcookems** [Azure/azure-sdk-for-php#94]
According to http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2, header field names are case-insensitive. However, that does not mean that header field names should be _changed_ willy-nilly.

For example, I have this code:

```
$meta = array("stringSize" => '' . strlen($data));
$this->service->setBlobMetadata($containerName, $blobName, $meta);
// On the wire, the outgoing header is:
//     X-Ms-Meta-Stringsize: 72
$meta2 = $this->service->getBlobMetadata($containerName, $blobName);
// On the wire, the incoming header is:
// x-ms-meta-Stringsize: 72
var_dump($meta2); // prints 'stringsize' => string '72'
```

There is a lot of case-changing going on here. It would be good for our framework to respect the user's specified capitalization, for consistency and interop (hence P1) with other frameworks that respect capitalization (such as REST, .NET, and Java frameworks).

**Comment by cweiske** [comment]
A feature request to HTTP_Request2 would be another option..
